apiVersion: v1
data: 
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXIzbTlyMis1eSo2ZzcjNXY2ei0qMXFiMF5ncGg4Jio0dkB6N3JuZCZocXBzYSY=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata: 
  name: api-secrets
type: Opaque