services:
  db:
    build: movies-db/.
    env_file:
      - movies-db/.env.db
    ports:
      - "5432:5432"
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db