name: Django CI

on:
  push:
    branches: [ master ]
    paths:
      - "movies_api/**"
  pull_request:
    branches: [ master ]
    paths:
      - "movies_api/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./movies_api
    strategy:
      matrix:
        db: [postgres]
        python-version: [3.8]
        include:
          - db: postgres
            db_user: postgres
            db_password: 'postgres'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres createuser -s runner
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        POSTGRES_NAME: ${{ matrix.db }}
        POSTGRES_USER: ${{ matrix.db_user }}
        POSTGRES_PASSWORD: ${{ matrix.db_password }}
      run: python manage.py test