name: Django CI

on:
  push:
    branches: [ master ]
    paths:
      - "movies_api/**"
  pull_request:
    branches: [ master ]
    paths:
      - "movies_api/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./movies_api
    services:
      postgres:
        image: postgres:16-alpine

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        POSTGRES_NAME: ${{ POSTGRES_DB }}
        POSTGRES_USER: ${{ POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ POSTGRES_PASSWORD}}
      run: python manage.py test